---
title: "Untitled"
author: "yuki"
date: "2024-01-04"
output: html_document
---
```{r}
library(dplyr)
```

```{r}
df <- list()
```

```{r}
file_list <- list.files(
  "../../4_Data_Extraction/4_2_Open_Data/", 
  pattern = "_raw.csv", 
  full.names = TRUE, recursive = TRUE
)

df <- setNames(
  lapply(file_list, function(file) read.csv(file)),
  sapply(file_list, basename)
)

rm(file_list)
names(df) <- paste0("[", seq_along(df), "] ", names(df))
```

```{r}
df[[13]] <- df[[13]] %>%
  dplyr::mutate(
    Paper = "51_1",
    ACC = respond3.ACC,
    RT  = respond3.RT,
  )
```

```{r}
df[[14]] <- df[[14]] %>%
  dplyr::mutate(
    Paper = "51_2",
    ACC = respond3.ACC,
    RT  = respond3.RT,
    Condition = condition1correct,
    Cue = condition1level
  )
```

```{r}
df[[15]] <- df[[15]] %>%
  dplyr::mutate(
    Paper = "51_2b",
    ACC = respond3.ACC,
    RT  = respond3.RT,
    Condition = condition1correct
  )
```

```{r}
temp <- dplyr::bind_rows(df[[13]],df[[14]],df[[15]])
selected_data <- temp %>% 
  select(Paper, Subject, Age, Handedness, Arouse.RESP, Valence.RESP, condition, 
         Cue, ACC, RT)

rm(temp)
```

```{r}

```

```{r}

```

