---
title: "2_Integrate_Data"
author: "czx"
date: "2024-01-16"
output: html_document
---
---
title: "Integrate"
author: "czx"
date: "2024-01-05"
output: html_document
---
```{r}
library(dplyr)
```

```{r}
df <- list()
```

```{r}
file_list <- list.files(
  "../../4_Data_Extraction/4_2_Open_Data/", 
  pattern = "_raw.csv", 
  full.names = TRUE, recursive = TRUE
)

df <- setNames(
  lapply(file_list, function(file) read.csv(file)),
  sapply(file_list, basename)
)

rm(file_list)
names(df) <- paste0("[", seq_along(df), "] ", names(df))
```

#Paper34

```{r}
df[[6]] <- df[[6]] %>%
  dplyr::mutate(
    Paper = "34_Exp1",
    Subject = subid,
    Handedness = handedness,
    Age = age
  )%>%
  dplyr::select(-subid, handedness,age)
```

```{r}
df[[7]] <- df[[7]] %>%
  dplyr::mutate(
    Paper = "34_2",
    Subject = subid,
    Handedness = handedness,
    Age = age
  )%>%
  dplyr::select(-subid, handedness,age)
```

```{r}
df[[8]] <- df[[8]] %>%
  dplyr::mutate(
    Paper = "34_3",
    Subject = subid,
    Handedness = handedness,
    Age = age
  )%>%
  dplyr::select(-subid, handedness,age)
```

```{r}
temp <- dplyr::bind_rows(df[[6]],df[[7]],df[[8]])
demographical_variable <- c("Paper", "Subject","Handedness")
selected_data_34 <- temp %>%
  dplyr::select(all_of(demographical_variable), everything())


rm(temp)
rm(demographical_variable)
```

#Paper51

```{r}
df[[13]] <- df[[13]] %>%
  dplyr::mutate(
    Paper = "51_1",
    ACC = respond3.ACC,
    RT  = respond3.RT,
  )
```

```{r}
df[[14]] <- df[[14]] %>%
  dplyr::mutate(
    Paper = "51_2",
    ACC = respond3.ACC,
    RT  = respond3.RT,
    Condition = condition1correct,
    Cue = condition1level
  )
```

```{r}
df[[15]] <- df[[15]] %>%
  dplyr::mutate(
    Paper = "51_2b",
    ACC = respond3.ACC,
    RT  = respond3.RT,
    Condition = condition1correct
  )
```

```{r}
temp <- dplyr::bind_rows(df[[13]],df[[14]],df[[15]])
selected_data_51 <- temp %>% 
  select(Paper, Subject, Age, Handedness, Arouse.RESP, Valence.RESP, 
         condition, Cue, ACC, RT)

rm(temp)
```

#Paper46

```{r}
#colnames(df[[9]])
df[[9]] <- df[[9]] %>%
  dplyr::mutate(
    Paper = "P46_Exp1_formal_raw",
    Subject = X1..Participant.Number,
    Handedness = X4..Handedness,
    Age = X3..Age,
    RT = rt,
    Gender = X2..Gender..M.F.,
    First_Lanugage = X5..First.Lanugage,
    Stimuli_Type = X6..Stimuli.Type.Self...Positive.Self...Negative.
  )%>%
  dplyr::select(-X1..Participant.Number,-X4..Handedness,-X3..Age,-rt,
                -X2..Gender..M.F.,-X5..First.Lanugage,
                -X6..Stimuli.Type.Self...Positive.Self...Negative.)

```

```{r}
df[[10]] <- df[[10]] %>%
  dplyr::mutate(
    Paper = "P46_Exp1_training_raw",
    Subject = X1..Participant.Number,
    Handedness = X4..Handedness,
    Age = X3..Age,
    RT = rt,
    Gender = X2..Gender..M.F.,
    First_Lanugage = X5..First.Lanugage,
    Stimuli_Type = X6..Stimuli.Type.Self...Positive.Self...Negative.
  )%>%
  dplyr::select(-X1..Participant.Number,-X4..Handedness,-X3..Age,-rt,
                -X2..Gender..M.F.,-X5..First.Lanugage,
                -X6..Stimuli.Type.Self...Positive.Self...Negative.)

```

```{r}
df[[11]] <- df[[11]] %>%
  dplyr::mutate(
    Paper = "P46_Exp2_formal_raw",
    Handedness = X4..Handedness,
    Age = X3..Age,
    RT = rt,
    Gender = X2..Gender,
    First_Lanugage = X5..First.Language,
    Stimuli_Type = X6..Stimuli.Type..Self...Negative.Self...Positive.,
  )%>%
  dplyr::select(-X4..Handedness,-X3..Age,-rt,-X2..Gender,-X5..First.Language,
                -X6..Stimuli.Type..Self...Negative.Self...Positive.)
```

```{r}
df[[12]] <- df[[12]] %>%
  dplyr::mutate(
    Paper = "P46_Exp2_training_raw",
    Handedness = X4..Handedness,
    Age = X3..Age,
    RT = rt,
    Gender = X2..Gender..M.F.,
    First_Lanugage = X5..First.Language,
    Stimuli_Type = X6..Stimuli.Type..SN.SP.,
  )%>%
  dplyr::select(-X4..Handedness,-X3..Age,-rt,-X2..Gender..M.F.,
                -X5..First.Language,-X6..Stimuli.Type..SN.SP.)
```

```{r}
# 将RT统一为数值型变量
# sapply(df[[9]], class)
# sapply(df[[10]], class)
# sapply(df[[11]], class)
# sapply(df[[12]], class)
# 继续检查其他数据框
df[[9]]$RT <- as.numeric(df[[9]]$RT)
df[[10]]$RT <- as.numeric(df[[10]]$RT)
df[[11]]$RT <- as.numeric(df[[11]]$RT)
df[[12]]$RT <- as.numeric(df[[12]]$RT)
# sapply(df[[9]], class)
# sapply(df[[10]], class)
# sapply(df[[11]], class)
# sapply(df[[12]], class)

```

```{r}
temp <- dplyr::bind_rows(df[[9]],df[[10]],df[[11]],df[[12]])
demographical_variable <- c("Paper", "Subject","Handedness","Age","RT",
                            "Gender","First_Lanugage","Stimuli_Type")
selected_data_46 <- temp %>%
  dplyr::select(all_of(demographical_variable), everything())
rm(temp)
rm(demographical_variable)
```

#Paper6

```{r}
df[[19]] <- df[[19]] %>%
  dplyr::mutate(
    Paper = "P6_Exp1",
    Subject = Pair.Number,
    RT = rt
  )%>%
  dplyr::select(-Pair.Number,-rt)
```

```{r}
temp <- df[[19]]
demographical_variable <- c("Paper", "RT")
selected_data_6 <- temp %>%
  dplyr::select(all_of(demographical_variable), everything())

rm(temp)
rm(demographical_variable)
```   

#Paper54

```{r}
df[[16]] <- df[[16]] %>%
  dplyr::mutate(
    Paper = "P54_Exp1",
    Handedness = hand,
  )%>%
  dplyr::select(-hand)
```

```{r}
df[[17]] <- df[[17]] %>%
  dplyr::mutate(
    Paper = "P54_Exp2",
    Handedness = hand,
  )%>%
  dplyr::select(-hand)
```

```{r}
df[[18]] <- df[[18]] %>%
  dplyr::mutate(
    Paper = "P54_Exp3",
  )
```

```{r}
temp <- dplyr::bind_rows(df[[16]],df[[17]],df[[18]])
demographical_variable <- c("Paper", "Subject","Handedness")
selected_data_54 <- temp %>%
  dplyr::select(all_of(demographical_variable), everything())

rm(temp)
rm(demographical_variable)
```

#Integrate

```{r}
selected_data_6$RT <- as.numeric(selected_data_6$RT)


All_Papers <- dplyr::bind_rows(selected_data_34,selected_data_51,
                               selected_data_46,selected_data_54,selected_data_6)
```

```{r}
# 指定存储的目录和文件名
output_directory <- getwd()
output_filename <- "All_Papers.csv"

# 创建完整的文件路径
output_path <- file.path(output_directory, output_filename)

# 将数据库导出为CSV文件
write.csv(All_Papers, output_path, row.names = FALSE)

rm(output_directory)
rm(output_filename)
rm(output_path)
rm(df)
```

