---
title: "3_Clean_Data"
author: "czx"
date: "2024-01-06"
output: html_document
---
```{r}
library(dplyr)
library(tidyr)
```

```{r}
df <- list()
```

```{r}
file_list <- list.files(
  "../../4_Data_Extraction/4_2_Open_Data/", 
  pattern = "_raw.csv", 
  full.names = TRUE, recursive = TRUE
)

df <- setNames(
  lapply(file_list, function(file) read.csv(file)),
  sapply(file_list, basename)
)

rm(file_list)
names(df) <- paste0("[", seq_along(df), "] ", names(df))
```

```{r}
#colnames(df[[9]])
df[[9]] <- df[[9]] %>%
  dplyr::mutate(
    Paper = "P46_Exp1_formal_raw",
    Subject = X1..Participant.Number,
    Handedness = X4..Handedness,
    Age = X3..Age,
    RT = rt,
    Gender = X2..Gender..M.F.,
    First_Lanugage = X5..First.Lanugage,
    Stimuli_Type = X6..Stimuli.Type.Self...Positive.Self...Negative.
  )%>%
  dplyr::select(-X1..Participant.Number,-X4..Handedness,-X3..Age,-rt,-X2..Gender..M.F.,-X5..First.Lanugage,-X6..Stimuli.Type.Self...Positive.Self...Negative.)

```

```{r}
df[[10]] <- df[[10]] %>%
  dplyr::mutate(
    Paper = "P46_Exp1_training_raw",
    Subject = X1..Participant.Number,
    Handedness = X4..Handedness,
    Age = X3..Age,
    RT = rt,
    Gender = X2..Gender..M.F.,
    First_Lanugage = X5..First.Lanugage,
    Stimuli_Type = X6..Stimuli.Type.Self...Positive.Self...Negative.
  )%>%
  dplyr::select(-X1..Participant.Number,-X4..Handedness,-X3..Age,-rt,-X2..Gender..M.F.,-X5..First.Lanugage,-X6..Stimuli.Type.Self...Positive.Self...Negative.)

```

```{r}
df[[11]] <- df[[11]] %>%
  dplyr::mutate(
    Paper = "P46_Exp2_formal_raw",
    Handedness = X4..Handedness,
    Age = X3..Age,
    RT = rt,
    Gender = X2..Gender,
    First_Lanugage = X5..First.Language,
    Stimuli_Type = X6..Stimuli.Type..Self...Negative.Self...Positive.,
  )%>%
  dplyr::select(-X4..Handedness,-X3..Age,-rt,-X2..Gender,-X5..First.Language,-X6..Stimuli.Type..Self...Negative.Self...Positive.)
```

```{r}
df[[12]] <- df[[12]] %>%
  dplyr::mutate(
    Paper = "P46_Exp2_training_raw",
    Handedness = X4..Handedness,
    Age = X3..Age,
    RT = rt,
    Gender = X2..Gender..M.F.,
    First_Lanugage = X5..First.Language,
    Stimuli_Type = X6..Stimuli.Type..SN.SP.,
  )%>%
  dplyr::select(-X4..Handedness,-X3..Age,-rt,-X2..Gender..M.F.,-X5..First.Language,-X6..Stimuli.Type..SN.SP.)
```

```{r}

# sapply(df[[9]], class)
# sapply(df[[10]], class)
# sapply(df[[11]], class)
# sapply(df[[12]], class)
# 继续检查其他数据框
df[[9]]$RT <- as.numeric(df[[9]]$RT)
df[[10]]$RT <- as.numeric(df[[10]]$RT)
df[[11]]$RT <- as.numeric(df[[11]]$RT)
df[[12]]$RT <- as.numeric(df[[12]]$RT)
sapply(df[[9]], class)
sapply(df[[10]], class)
sapply(df[[11]], class)
sapply(df[[12]], class)

```

```{r}
temp <- dplyr::bind_rows(df[[9]],df[[10]],df[[11]],df[[12]])
demographical_variable <- c("Paper", "Subject","Handedness","Age","RT","Gender","First_Lanugage","Stimuli_Type")
selected_data1 <- temp %>%
  dplyr::select(all_of(demographical_variable), everything())
rm(temp)
```




