---
title: "5_Clean_Data"
author: "czx"
date: "2024-01-07"
output: html_document
---

```{r}
library(dplyr)
library(tidyr)
```

```{r}
df <- list()
```

```{r}
file_list <- list.files(
  "../../4_Data_Extraction/4_2_Open_Data/", 
  pattern = "_raw.csv", 
  full.names = TRUE, recursive = TRUE
)

df <- setNames(
  lapply(file_list, function(file) read.csv(file)),
  sapply(file_list, basename)
)

rm(file_list)
names(df) <- paste0("[", seq_along(df), "] ", names(df))
```

```{r}
df[[16]] <- df[[16]] %>%
  dplyr::mutate(
    Paper = "P54_Exp1",
    Handedness = hand,
  )%>%
  dplyr::select(-hand)
```

```{r}
df[[17]] <- df[[17]] %>%
  dplyr::mutate(
    Paper = "P54_Exp2",
    Handedness = hand,
  )%>%
  dplyr::select(-hand)
```

```{r}
df[[18]] <- df[[18]] %>%
  dplyr::mutate(
    Paper = "P54_Exp3",
  )
```

```{r}
temp <- dplyr::bind_rows(df[[16]],df[[17]],df[[18]])
demographical_variable <- c("Paper", "Subject","Handedness")
selected_data <- temp %>%
  dplyr::select(all_of(demographical_variable), everything())

rm(temp)
rm(demographical_variable)
```