---
title: "Self-Prioritization Effects Database"
author: "Author First M. Last"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
  pdf_document:
    toc: true
    number_sections: true
---

# Abstract

\ \ \ \ Self-Prioritization Effects play an important role in helping us understand how self-relevance influences human actions and thoughts. To better understand this process, we created a large database of Self-Prioritization Effects studies based on Sui's paradigm. The data from each study are structured in a common, easy-to-use format that can be imported and analyzed using multiple software packages. Each dataset is accompanied by an explanation regarding the nature of the collected data. As of publication, the Self-Prioritization Effects Database (available at [GitHub Repository](https://github.com/Chuan-Peng-Lab/SPE_Database)) contains 145 datasets with data from more than 8,700 participants. We demonstrate the usefulness of this collection in four analyses that provide precise estimations of several foundational self-related effects.

**Keywords**: Self-Prioritization Effects; Database

# Introduction

\ \ \ \ Recently, more and more researchers have become interested in how self-relevance influences human actions and thoughts. An elegant experimental paradigm (Sui et al., 2012) shows that when stimuli are related to ourselves, we tend to respond with greater accuracy and speed. For example, when the concept of "me" is associated with a triangle, recognition is faster and more accurate than when the shape is associated with "others". This suggests that the self-concept has priority in early perceptual processing, known as the Self-Prioritization Effect (SPE) in shape-label matching tasks.

\ \ \ \ The Self-Prioritization Effect is an important topic in psychology, focusing on how individuals process self-relevant information. Since 2009, research by Sui and colleagues has shown that individuals prioritize self-related stimuli in attention tasks, laying the foundation for subsequent studies. In 2012, Sui and colleagues introduced the shape-label matching task, which standardized the experimental paradigm for studying self-relevance and made the research more systematic and operational.In 2013, Sui et al. further explored the neural mechanisms of SPE, revealing that self-related stimuli activate the ventromedial prefrontal cortex (vmPFC), which is involved in self-representation, and influence functional coupling in domain-specific brain regions. This finding provided crucial insights into the neural basis of SPE. By 2015, Sui and Humphreys proposed that SPE may impact multiple stages of information processing, including attention allocation, memory, and decision-making, broadening the scope of SPE research.In 2016, Liu et al. confirmed that SPE plays a role in decision-making, showing that self-relevant stimuli can regulate decision processes. Later, in 2017, Golubickis and Schafer examined the interactions between SPE and factors like the reward and emotional value of stimuli, adding new dimensions to the understanding of SPE's complexity.

\ \ \ \ The Self-Prioritization Effects Database has been developed to provide a comprehensive resource for researchers interested in this phenomenon. It includes a wide range of experimental data, stimuli, and some relevant variable that have been used in studies on self-relevance and its impact on cognition and behavior. The database is designed to be user-friendly, allowing researchers to easily search for and access the raw data they need for their own experiments. This  paper aims to facilitate the replication of studies, enhance the consistency of research findings, and promote collaboration among researchers in the field. By providing a standardized set of tools and data, the database seeks to advance our understanding of how self-prioritization effects influence various aspects of human cognition and behavior.


## Details of the Database

The Self-Prioritization Effects Database is hosted on the [Open Science Framework (OSF)](https://osf.io/s46pr/) website. Each dataset is represented by two folders: **Raw_Data** and **Clean_Data**.

(Basic Pic for Database flod tructure)


-   The **Raw_Data** folder contains the original data from the study.
-   The **Clean_Data** folder includes processed data files in `.csv` format and a corresponding codebook in `.xlsx` format.

Each study includes a README file, which outlines the authors, citation, participants, procedure, and data files.

## Example Uses of the Database

The Self-Prioritization Effects Database can be used for a variety of purposes, such as: 1. Developing and testing new models of Self-Prioritization Effects. 2. Comparing the effects of different demographic variables on SPE (e.g., gender, nationality, area). 3. Replicating studies to validate findings. 4. Conducting meta-analyses to estimate the size of SPE across different tasks and populations.

Below are some example analyses demonstrating the utility of the database.

### How the Self-prioritization Effect is related to RT on the basis of baseline.
- 思路：用不同Identity与Self的差值画图
- 目的：展现出与不同Identity相比的SPE的程度
- P1(横坐标是RT,纵坐标是Correlation with Cohen's d-Self-Friend in RT. )
- P2(横坐标是RT,纵坐标是Correlation with Cohen's d-Self-Close in RT. )
- P3(横坐标是RT,纵坐标是Correlation with Cohen's d-Self-Stranger in RT. )
  
### Serial dependence in SPE RT.

- 思路：模仿Confidence Database,看不同的Trial、ACC对SPE的影响
- 目的：展现出可能会影响SPE的其他影响
- P4(横坐标是RT/ACC,纵坐标是Cohen's d)
- P5(横坐标是Number of trials,纵坐标是Cohen's d)
- P6(横坐标是Average accuracy (%),纵坐标是Cohen's d)
- P7(横坐标是Median choice RT (s),纵坐标是Cohen's d)

### The Nonmatching Condition with SPE.
- 思路：探索Nonmatching条件下，是否存在自我优势效应
- 目的：探索自我优势效应的范围
- P8(Nonmatching条件下，横坐标是ACC,纵坐标是RT)


## Conclusion

The Self-Prioritization Effects Database provides researchers with a wealth of data to explore the cognitive mechanisms underlying self-relevance. By making these datasets publicly available, we hope to facilitate further research and collaboration in this field.

## References

-   Sui, J., He, X., & Humphreys, G. W. (2012). **Perceptual effects of self-relevance: Evidence from perceptual matching**. *Journal of Experimental Psychology: Human Perception and Performance*, 38(5), 1105-1117. DOI: <https://doi.org/10.1037/a0029792>

-   Sui, J., & Humphreys, G. W. (2013). **Self-referential processing is distinct from semantic elaboration: evidence from long-term memory effects in a patient with amnesia and semantic impairments.**.*Neuropsychologia*,51(13), 2663–2673. https://doi.org/10.1016/j.neuropsychologia.2013.07.025
-   Humphreys, G. W. , &  Sui, J. . (2015). **Broadbent lecture at the 18th ESCOP conference, Budapest, Hungary: The salient self: Social saliency effects based on self-bias.**
-   Liu, Minghui, Sui, Jie, Mevorach, & Carmel, et al. (2015). **The salient self: the left intraparietal sulcus responds to social as well as perceptual-salience after self-association.**.*Cerebral Cortex.*
-   Clea, Desebrock, Jie, Sui, Charles, & Spence. (2018). **Self-reference in action: arm-movement responses are enhanced in perceptual matching.**.*Acta Psychologica.*